### PR TITLE
Bug 1219732: fix page-worker test addon manifest for JPM

### PR DESCRIPTION
**Pull request by jaragunde**
Patch to modify the manifest in one of the test addons so it can be run with jpm. Fixes [bug report #1219732](https://bugzilla.mozilla.org/show_bug.cgi?id=1219732).

### CODE REVIEW

**Comment by benmccann** [comment]
@KWierso @jsantell would you be able to review? thanks!

**Comment by KWierso** [comment]
This looks simple enough and right to me, but I'm not a reviewer for this code, and I haven't really kept up with SDK stuff since the move to JPM.

**Comment by benmccann** [comment]
@jsantell @Mossop would you be able to review? thanks!

**Comment by benmccann** [comment]
@jsantell @Mossop @erikvold would you be able to review? thanks!

**Comment by erikvold** [comment]
@benmccann @mozila fired me and removed my permissions, so I can't review it now.

**Pull request closed without merging**
